### ISSUE TITLE
Languages files not included in source tree

### ISSUE THREAD

**Issue by KevinField** [Germanunkol/Wiki-Based-RPG#2]
I'm a bit confused as to why this is...the last commit removed them, but they're still included in the 0.6 distribution zip.  So it seems it would not run as-is just downloading the source tree.

**Comment by KevinField** [comment]
At least the DefaultLanguages should be included, it seems.

**Comment by KevinField** [comment]
This was fixed in the merge.

**Comment by Germanunkol** [comment]
I honestly don't remember why I did this. Your fix seems to be the way to go.
